fixing bigdecimal dependency for ruby 2.7
It seems that for ruby-2.7 we should fix bigdecimal to ~> 1.4 as this page tells us

https://github.com/ruby/bigdecimal#which-version-should-you-select

Otherwize the error below occurs. Still trying to reproduce successful spec run

Failure/Error: require 'active_support/all'

NoMethodError:
  undefined method `new' for BigDecimal:Class
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/core_ext/object.rb:3:in `require'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/core_ext.rb:2:in `require'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/core_ext.rb:1:in `each'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/core_ext.rb:1:in `<top (required)>'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/all.rb:3:in `require'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/activesupport-4.2.11/lib/active_support/all.rb:3:in `<top (required)>'
 ./lib/protector.rb:1:in `require'
 ./lib/protector.rb:1:in `<top (required)>'
 /Users/kireto/.rvm/gems/ruby-2.7.6/gems/bundler-2.3.23/lib/bundler.rb:187:in `require'
 ./spec/spec_helpers/boot.rb:17:in `<top (required)>'
 ./spec/lib/protector/dsl_spec.rb:1:in `require'
 ./spec/lib/protector/dsl_spec.rb:1:in `<top (required)>'